import jsPDF from "jspdf";

export function generatePostmortemPDF(postmortem) {
  const doc = new jsPDF();

  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - margin * 2;

  let y = 20;

  const checkPage = (space = 20) => {
    if (y + space > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }
  };

  const heading = (text) => {
    checkPage(30);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(text, margin, y);

    y += 9;
  };

  const paragraph = (text, size = 10) => {
    checkPage(25);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);

    const lines = doc.splitTextToSize(text, contentWidth);

    doc.text(lines, margin, y);

    y += lines.length * 5 + 6;
  };

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Incident Postmortem Report", margin, y);

  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    margin,
    y
  );

  y += 15;

  // Incident
  heading("Incident");

  paragraph(`Incident ID: ${postmortem.incidentId}`);
  paragraph(`Title: ${postmortem.title}`);
  paragraph(`Service: ${postmortem.service}`);
  paragraph(`Severity: ${postmortem.severity}`);
  paragraph(`Status: ${postmortem.status}`);

  // Timeline
  heading("Incident Timeline");

  postmortem.timeline.forEach((event) => {
    paragraph(`${event.step} — ${event.time}`);
    paragraph(event.detail);
  });

  // Root Cause
  heading("Root Cause");
  paragraph(postmortem.rootCause);

  // Remediation
  heading("Remediation");
  paragraph(postmortem.remediation);

  // Resolution
  heading("Resolution");
  paragraph(postmortem.resolution);

  // Lessons
  heading("Lessons Learned");

  postmortem.lessons.forEach((lesson, index) => {
    paragraph(`${index + 1}. ${lesson}`);
  });

  // Footer
  checkPage(20);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);

  doc.text(
    "Generated by OPS CONTROL — AI Incident Platform",
    margin,
    pageHeight - 10
  );

  doc.save(
    `postmortem-${postmortem.incidentId}.pdf`
  );
}